version: '3'

services:
  krabbitmq:
    hostname: krabbitmq
    image: rabbitmq:latest
    volumes:
      - "./rabbitmq.conf:/etc/rabbitmq/rabbitmq.conf"
    ports:
      - "5672:5672"
  rest:
    build: app
    command: uvicorn app.main:app --host 0.0.0.0
    volumes:
      - .:/app
    ports:
      - 8000:8000
    restart: on-failure
    depends_on:
        - krabbitmq
    links:
        - krabbitmq



